<?php
namespace AppBundle\Repository;

use AppBundle\Entity\Lesson;
use AppBundle\Entity\Season;
use Doctrine\ORM\EntityRepository;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository
{
    /**
     * @param Season $season
     * @return Lesson[]
     */
    public function findBySeason(Season $season)
    {
        return $this
            ->createQueryBuilder('l')
            ->andWhere('l.date >= :start')
            ->andWhere('l.date <= :stop')
            ->setParameter('start', $season->getStart()->format('Y-m-d'))
            ->setParameter('stop', $season->getStop()->format('Y-m-d'))
            ->getQuery()
            ->getResult();
    }
}
