services:
    app.form.type.stat_member_segment:
        class: AppBundle\Form\StatMemberSegmentType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
