services:
    app.form.type.stat_account_summary:
        class: AppBundle\Form\StatAccountSummaryType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
