services:
    app.form.type.stat_member_origin:
        class: AppBundle\Form\StatMemberOriginType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    app.form.type.stat_member_segment:
        class: AppBundle\Form\StatMemberSegmentType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    app.form.type.stat_member_signature:
        class: AppBundle\Form\StatMemberSignatureType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
