services:
    app.form.type.choice_season:
        class: AppBundle\Form\Type\ChoiceSeasonType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type }
    app.form.type.date_picker:
        class: AppBundle\Form\Type\DatePickerType
        arguments: [ "@request_stack" ]
        tags:
            - { name: form.type }
    app.lesson_manager:
        class: AppBundle\Utils\LessonManager
        arguments: [ "@doctrine.orm.entity_manager" ]
    app.level_manager:
        class: AppBundle\Utils\LevelManager
        arguments: [ "@doctrine.orm.entity_manager" ]
    app.locale_listener:
        class: AppBundle\Listener\LocaleListener
        arguments:
            -
                - en
                - fr
        tags:
            - { name: kernel.event_subscriber }
    app.member_manager:
        class: AppBundle\Utils\MemberManager
        arguments: [ "@doctrine.orm.entity_manager", "%member_photo_directory%" ]
    app.rank_manager:
        class: AppBundle\Utils\RankManager
        arguments: [ "@doctrine.orm.entity_manager", "%rank_image_directory%" ]
    app.search_manager:
        class: AppBundle\Utils\SearchManager
        arguments: [ "@doctrine.orm.entity_manager" ]
    app.security.authentication_listner:
        class: AppBundle\Listener\AuthenticationListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_subscriber }
    app.transaction_manager:
        class: AppBundle\Utils\TransactionManager
        arguments: [ "@doctrine.orm.entity_manager", "%transaction_copy_directory%" ]
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
