services:
    app.form.type.choice_season:
        class: AppBundle\Form\Type\ChoiceSeasonType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type }
    app.lesson_manager:
        class: AppBundle\Utils\LessonManager
        arguments: [ "@doctrine.orm.entity_manager" ]
    app.member_manager:
        class: AppBundle\Utils\MemberManager
        arguments: [ "@doctrine.orm.entity_manager", "%member_photo_directory%" ]
    app.rank_manager:
        class: AppBundle\Utils\RankManager
        arguments: [ "@doctrine.orm.entity_manager", "%rank_image_directory%" ]
    app.search_manager:
        class: AppBundle\Utils\SearchManager
        arguments: [ "@doctrine.orm.entity_manager" ]
    app.security.authentication_listner:
        class: AppBundle\Listener\AuthenticationListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_subscriber }
    app.transaction_manager:
        class: AppBundle\Utils\TransactionManager
        arguments: [ "@doctrine.orm.entity_manager", "%transaction_copy_directory%" ]
